---
- name: Install BigFix GPG Key
  rpm_key:
    state: present
    key: http://software.bigfix.com/download/bes/95/RPM-GPG-KEY-BigFix-9-V2

- name: Install BigFix Client
  yum:
    name: "/tmp/{{ bigfix_client_file_dest }}"
    state: present
